# Generated by Django 3.1.4 on 2020-12-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
