# Generated by Django 3.1.4 on 2020-12-27 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201226_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='start_bid',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
