# Generated by Django 3.1.4 on 2020-12-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201227_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bids',
            new_name='bid',
        ),
    ]
