# Generated by Django 3.1.4 on 2020-12-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
