# Generated by Django 3.1.4 on 2020-12-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(choices=[('OR', 'Others'), ('HO', 'Home'), ('AP', 'Appliances'), ('TO', 'Toys'), ('CO', 'Computers'), ('COL', 'Collectables')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(blank=True, default='auctions/imgs/no_img.jpg', max_length=500),
        ),
    ]
