# Generated by Django 3.1.4 on 2020-12-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201229_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/480px-No_image_available.svg.png', max_length=500),
        ),
    ]
