# Generated by Django 3.1.4 on 2020-12-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201229_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='category',
            field=models.CharField(choices=[('Others', 'Others'), ('Home', 'Home'), ('Appliances', 'Appliances'), ('Toys', 'Toys'), ('Computers', 'Computers'), ('Collectables', 'Collectables')], max_length=100),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
